<!DOCTYPE html>
<html>
<head>
<?php
    $this->load->view('/public/linker',array(
        'css'=>array(),
        'js' =>array(),
    ));
    $ctrl_url = base_url('customer/exam_regist');
?>
<style>
    .required {
        color: red;
    }
    .fullwidth {
        width: 100%;
    }
</style>
</head>
<body>
<div id="p-edit" class="easyui-panel" title="" fit="true" border="false">
    <div class="easyui-layout" fit="true">
        <div data-options="region:'north'" style="height:28px;overflow:hidden;background-color:#dddddd;" border="false">
            <button class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="javascript:window.parent.change_panel('dg');">返回</button>
        </div>
        <div data-options="region:'center'" style="overflow:hidden;" border="false">
            <div id="p-edit-login" class="easyui-panel" fit="true" border="false" style="overflow:auto;">
                <form id="fm-edit" method="post" style="width:90%; margin:10px;">
                    <input type="hidden" name="actionxm" value="<?php echo $actionxm; ?>" />
                    <input type="hidden" name="id" value="<?php echo get_value($info, 'id', '0'); ?>">
                    <table class="fm-table" cellpadding="8px">
                        <colgroup>
                            <col width="240px"  />
                            <col width="470px" />
                            <col width="*" />
                        </colgroup>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                体检名称：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="name" value="<?php echo get_value($info, 'name', ''); ?>" style="width:100%" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                客户名称：
                            </td>
                            <td>
                                <select class="easyui-combobox js_uid" name="uid" style="width:50%;">
                                    <?php echo get_value($info, 'customerTree', ''); ?>
                                </select>
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                结果：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="result" data-options="multiline:true" value="<?php echo get_value($info, 'result', ''); ?>" style="width:100%;height:150px">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                参考上限：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="upper_limit" data-options="multiline:true" value="<?php echo get_value($info, 'upper_limit', ''); ?>" style="width:100%;height:150px">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required"></span>
                                参考下限：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="lower_limit" data-options="multiline:true" value="<?php echo get_value($info, 'lower_limit', ''); ?>" style="width:100%;height:150px">
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center;" colspan="2">
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_save()">保存</button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_reset()">重置</button>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function() {
        $('.js_uid').combobox('setValue', <?php echo get_value($info, 'uid', 0); ?>);
    });

    // 保存登录tips信息
    function do_save() {
        $('#fm-edit').form('submit', {
            url: '<?php echo $ctrl_url; ?>/post',
            onSubmit: function() {
                if($('#fm-edit input[name="name"]').val()=='') {
                    $.messager.alert('操作提示', '请输入体检名称');
                    return false;
                }
                if($('.js_uid').combobox('getValue')<=0) {
                    $.messager.alert('操作提示', '请选择体检客户名称');
                    return false;
                }
                return true;
            },
            success: function(result) {
                var result = $.parseJSON(result);
                var actionxm = $('#fm-edit input[name="actionxm"]').val();
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    cur_tips_id = result.data.tips_id;
                    $('#fm-edit input[name="actionxm"]').val('update');
                    $('#fm-edit input[name="tips_id"]').val(cur_tips_id);
                    $.messager.alert('操作提示', '保存成功', 'info', function() {
                        window.parent.dg_reload();
                        window.parent.change_panel('dg');
                    });
                }
            }
        })
    }
</script>

</body>
</html>
