<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array('jquery.easyui.extension/datagrid-detailview'),
        ));
        $ctrl_url = base_url('customer/ledger');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .dv-table td {
        border:0;
    }
    .dv-label {
        font-weight:bold;
        color:#15428B;
        width:100px;
    }
    .dv-table td {
        padding-bottom: 8px;
    }
    </style>
</head>
<body>
    <div id="p-dg" class="easyui-panel" title="客户台账管理" fit="true" border="false">
        <table id="dg" class="easyui-datagrid" title=""
               fit="true" border="false" plain="true"
               toolbar="#toolbar" multiSort="true"
               rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
               singleSelect="true" remote>
            <thead>
                <tr>
                    <th data-options="sortable:true,field:'id',width:50">编号</th>
                    <th data-options="sortable:true,field:'name',width:80">姓名</th>
                    <th data-options="sortable:true,field:'branch_name',width:80">所属分店</th>
                    <th data-options="sortable:true,field:'cust_name',width:80">所属业务员</th>
                    <th data-options="sortable:true,field:'age',width:50">年龄</th>
                    <th data-options="sortable:true,field:'sex',width:50" formatter="format_sex">性别</th>
                    <th data-options="sortable:true,field:'phone',width:100">电话</th>
                    <th data-options="sortable:true,field:'has_trade',width:70" formatter="format_has_trade">成交与否</th>
                    <th data-options="sortable:true,field:'create_user_name',width:80">创建人</th>
                    <th data-options="sortable:true,field:'create_time',width:130">创建时间</th>
                    <th data-options="sortable:true,field:'update_user_name',width:80">更新人</th>
                    <th data-options="sortable:true,field:'update_time',width:130">更新时间</th>
                </tr>
            </thead>
        </table>

        <div id="toolbar" style="padding:2px 3px;">
            <form id="fm-search" method="post" novalidate>
                <div style="margin:3px 0;">
                    交易与否
                    <select id="has_trade" class="easyui-combobox" style="width:100px;" name="has_trade" data-options="valueField:'id', textField: 'name'" panelHeight="auto"></select>
                    <?php if(!!$showBid) { ?>
                    所属分店：
                    <select id="branch_id" class="easyui-combobox" style="width:200px;" name="branch_id" data-options="valueField:'id',textField:'name'" panelHeight="auto" >
                    </select>
                    <?php } ?>
                    姓名：
                    <input id="title" class="easyui-textbox" style="width:100px" name="name">
                    电话：
                    <input id="title" class="easyui-textbox" style="width:100px" name="phone">
                    <span class="split-line">|</span>
                    <a class="easyui-linkbutton" iconCls="icon-search" onclick="do_search()" style="width:60px">搜索</a>
                </div>
            </form>
        </div>
    </div>

    <?php $this->load->view('customer/distribut_edit');?>

    <script type="text/javascript">
    $(function() {
        $('#dg').datagrid({
            view: detailview,
            detailFormatter:function(index,row){
                return '<div class="ddv" style="padding:10px 0;"></div>';
            },
            onExpandRow: function(index,row){
                var ddv = $(this).datagrid('getRowDetail',index).find('div.ddv');
                ddv.panel({
                    border:false,
                    cache:false,
                    href: "<?php echo $ctrl_url.'/get?actionxm=details'; ?>&id=" + row.id,
                    onLoad:function(){
                        $('#dg').datagrid('fixDetailRowHeight',index);
                    }
                });
                $('#dg').datagrid('fixDetailRowHeight',index);
            }
        });

        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj
            });
        }, 100);

        // 加载模块名称下拉框
        $.ajax({
            url: '<?php echo base_url("sys/branch/get?actionxm=get_list"); ?>',
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                var new_data = new Array();
                new_data.push({"name":"不限", "id":-1, "selected":true});
                $.each(data, function(i, n) {
                    if(n.is_leaf) {
                        new_data.push({"name":'&nbsp;&nbsp;&nbsp;&nbsp;|-'+n.name, 'id': n.id});
                    } else {
                        new_data.push({"name":n.name, 'id': n.id});
                    }
                });
                $("#branch_id").combobox("loadData", new_data);
            }
        });

        $('#branch_id').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.name.replace(/&nbsp;/ig, '');
                $('#branch_id').combobox('setText', n);
            }
        });

        var json = new Array();
        json.push({'name': '不限', 'id': -1, 'selected': true}, {'name': '已交易', 'id': 1}, {'name': '未交易', 'id': 2});
        $('#has_trade').combobox('loadData', json);
    });

    function open_update(){
        var info = $('#dg').datagrid('getSelected');
        if(info==null){
            $.messager.alert('操作提示','请选择需要编辑的记录!','warning');
            return;
        }
        load_sale(info.custId);
        var fm_data = {
            actionxm: 'updateSale',
            id: info.id
        };
        $('#fm-edit').form('load', fm_data);
        $('#dlg-edit').dialog('setTitle', '客户分配').dialog('open');
    }

    // 搜索操作
    function do_search() {
        var fm_data = $('#fm-search').form('getData');
        $('#dg').datagrid('options').queryParams = {actionxm:'search', rs:fm_data};
        $('#dg').datagrid('reload');
    }

    function do_save(){
        $('#fm-edit').form('submit',{
            onSubmit: function(){
                return $(this).form('validate');
            },
            success: function(result){
                var result = eval('('+result+')');
                if (result.success==false){
                    $.messager.alert('操作提示',result.data,'warning');
                } else {
                    $('#dlg-edit').dialog('close');
                    $('#dg').datagrid('reload');
                }
            }
        });
    }

    // 格式化性别
    function format_sex(value, row) {
        var rtn = '';
        switch(value) {
            case '1':
                rtn = '<span style="color:green;">男</span>';
                break;
            case '2':
                rtn = '<span style="color:red;">女</span>';
                break;
            default:
                rtn = '<span style="color:grey;">未知</span>';
                break;
        }
        return rtn;
    }

    // 格式化交易情况
    function format_has_trade(value, row) {
        var rtn = '';
        switch(value) {
            case true:
                rtn = '<span style="color: green;">已交易</span>';
                break;
            case false:
                rtn = '<span style="color: red;">未交易</span>';
                break;
            default:
                rtn = '<span style="color: grey;">未知</span>';
                break;
        }
        return rtn;
    }

    function load_sale(id) {
        // 加载模块名称下拉框
        $.ajax({
            url: '<?php echo base_url("sys/user/get?actionxm=get_list"); ?>',
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                var new_data = new Array();
                $.each(data, function(i, n) {
                    if(n.user_id==id) {
                        console.log(n);
                        console.log(id);
                        new_data.push({"name":n.user_name+'['+n.bname+']', 'id': n.user_id, "selected":true});
                    } else {
                        new_data.push({"name":n.user_name+'['+n.bname+']', 'id': n.user_id});
                    }
                });
                $("#selectSale").combobox("loadData", new_data);
            }
        });
    }
    </script>
</body>
</html>

