<div id="dlg-edit" class="easyui-dialog" style="width:400px;height:260px;padding:10px 20px"
    closed="true" modal="true" buttons="#dlg-edit-buttons" title="编辑表单">
    <form id="fm-edit" method="post" action="<?php echo base_url('transaction/package_order/post')?>" novalidate>
        <input type="hidden" name="actionxm" value="">
        <table class="fm-table" cellpadding="4px">
            <colgroup>
                <col width="150px" /><col width="*" />
            </colgroup>
            <tr>
                <td>套餐:</td>
                <td>
                    <select id="pid" class="easyui-combobox" style="width:100%;" name="pid" data-options="valueField:'id',textField:'name'" panelHeight="auto" >
                </td>
            </tr>
            <tr>
                <td>用户:</td>
                <td>
                    <select id="uid" class="easyui-combobox" style="width:100%;" name="uid" data-options="valueField:'id',textField:'name'" panelHeight="auto" >
                </td>
            </tr>
            <tr>
                <td>折扣:</td>
                <td><input class="text" name="discount" value="" placeholder="如：七折填写70。不填为没有折扣" required="true"></td>
            </tr>
            <tr>
                <td>调理开始时间:</td>
                <td><input class="easyui-datebox" name="care_time" value="" style="width:100%"></td>
            </tr>
            <tr>
                <td>餐包数量:</td>
                <td><input class="text" name="food_num" value="0" required=""></td>
            </tr>
        </table>
    </form>
</div>
<div id="dlg-edit-buttons">
    <button class="easyui-linkbutton w90" iconCls="icon-ok" onclick="do_save()">确定</button>
    <button class="easyui-linkbutton w90" iconCls="icon-cancel" onclick="javascript:$('#dlg-edit').dialog('close')">取消</button>
</div>
