<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array(),
        ));
    ?>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="分店管理"
           fit="true" border="false" plain="true"
           url="<?php echo base_url('sys/branch/get?actionxm=search')?>" method="post"
           toolbar="#toolbar" multiSort="true"
           rownumbers="false" pagination="false"
           singleSelect="true" remote>
        <thead>
            <tr>
                <th data-options="sortable:true,field:'id',width:80">分店ID</th>
                <th data-options="sortable:true,field:'name',width:200" formatter="format_name">名称</th>
                <th data-options="sortable:true,field:'sort',width:80">排序</th>
                <th data-options="sortable:true,field:'create_user_name',width:100">创建人</th>
                <th data-options="sortable:true,field:'create_time',width:120">创建时间</th>
                <th data-options="sortable:true,field:'update_user_name',width:100">更新人</th>
                <th data-options="sortable:true,field:'update_time',width:120">更新时间</th>
            </tr>
        </thead>
    </table>

    <div id="toolbar">
        <button class="easyui-linkbutton" iconCls="icon-add"    plain="true" onclick="open_insert()">添加</button>
        <button class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="do_delete()">删除</button>
        <button class="easyui-linkbutton" iconCls="icon-edit"   plain="true" onclick="open_update()">修改</button>
    </div>

    <?php $this->load->view('sys/branch_edit');?>

    <script type="text/javascript">

    // 格式化分店名称为树状
    function format_name(value, row) {
        if(row.level>0) {
            return '<span style="display:inline-block;padding-left:'+(20*row.level)+'px">|-'+value+'</span>';
        } else {
            return value;
        }
    }

    function reload_pmenu() {
        var dg_rows = $('#dg').datagrid('getRows');
        var options = '<option value="0">---无---</option>';
        var name = '';
        for(var x in dg_rows) {
            name = dg_rows[x].name;
            if(dg_rows[x].level>0) {
                name = (new Array(dg_rows[x].level+1).join('&nbsp;&nbsp;&nbsp;&nbsp;'))+'|-'+name;
            }
            options+='<option value="'+dg_rows[x].id+'">'+name+'</option>';
        }
        $('#combo_pmenu').html(options);
    }

    // 打开添加窗口
    function open_insert() {
        reload_pmenu();
        $('#fm-edit').form('clear').form('load', {actionxm:'insert', id:'系统编号', pid:0});
        $('#dlg-edit').dialog('setTitle', '分店添加').dialog('open');
    }

    // 打开修改窗口
    function open_update() {
        reload_pmenu();
        var info = $('#dg').datagrid('getSelected');
        if(info==null) {
            $.messager.alert('操作提示', '请选择需要编辑的数据!', 'warning');
            return;
        }
        var fm_data = {
                actionxm: 'update',
                id: info.id,
                pid: info.pid,
                name: info.name,
                sort: info.sort
        };
        $('#fm-edit').form('load', fm_data);
        $('#dlg-edit').dialog('setTitle', '分店编辑').dialog('open');
    }

    // 保存操作
    function do_save() {
        $('#fm-edit').form('submit', {
            onSubmit: function() {
                return $(this).form('validate');
            },
            success: function(result) {
                var result = eval('('+result+')');
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    $('#dlg-edit').dialog('close');
                    $('#dg').datagrid('reload');
                }
            }
        });
    }

    // 删除操作
    function do_delete() {
        var info = $('#dg').datagrid('getSelected');
        if(info==null) {
            $.messager.alert('操作提示', '请选择需要删除的分店!', 'warning');
            return;
        }
        $.messager.confirm('操作提示', '你确定要删除此分店信息吗?', function(r) {
            if(r) {
                $.post('<?php echo base_url('sys/branch/post')?>', {id:info.id, actionxm:'delete'}, function(result) {
                    if(result.success) {
                        $('#dg').datagrid('reload');
                    } else {
                        $.messager.alert('操作提示', '删除成功');
                    }
                }, 'json');
            }
        });
    }
    </script>
</body>
</html>
