<!DOCTYPE html>
<html>
<head>
<?php
    $this->load->view('/public/linker',array(
        'css'=>array(),
        'js' =>array(),
    ));
    $ctrl_url = base_url('aftersale/follow');
?>
<style>
    .required {
        color: red;
    }
</style>
</head>
<body>
<div id="p-edit" class="easyui-panel" title="" fit="true" border="false">
    <div class="easyui-layout" fit="true">
        <div data-options="region:'north'" style="height:28px;overflow:hidden;background-color:#dddddd;" border="false">
            <button class="easyui-linkbutton" iconCls="icon-back" plain="true" onclick="javascript:window.parent.change_panel('dg');">返回</button>
        </div>
        <div data-options="region:'center'" style="overflow:hidden;" border="false">
            <div id="p-edit-login" class="easyui-panel" fit="true" border="false" style="overflow:auto;">
                <form id="fm-edit" method="post" style="width:90%; margin:10px;">
                    <input type="hidden" name="actionxm" value="<?php echo $actionxm; ?>" />
                    <input type="hidden" name="id" value="<?php echo get_value($info, 'id', '0'); ?>">
                    <table class="fm-table" cellpadding="8px">
                        <colgroup>
                            <col width="240px" />
                            <col width="470px" />
                            <col width="*" />
                        </colgroup>
                        <tr>
                            <td class="label" style="color:red;">
                                <h3>基础信息</h3>
                            </td>
                            <td colspan="2">
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                第几周：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="name" value="<?php echo get_value($info, 'name', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                第几日：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="name" value="<?php echo get_value($info, 'name', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                体重（KG）：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                试纸：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                血压：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                血糖：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                睡眠：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                大小便：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label" style="color:red;">
                                <h3>饮食信息</h3>
                            </td>
                            <td colspan="2">
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                早餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                加餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                午餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                加餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                晚餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                加餐时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                食物：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label" style="color:red;">
                                <h3>其他信息</h3>
                            </td>
                            <td colspan="2">
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                五行操时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                时长：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                泡脚时间：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                其他运动：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                饮水（ML）：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <span class="required">*</span>
                                体会：
                            </td>
                            <td>
                                <input class="easyui-textbox" name="age" value="<?php echo get_value($info, 'age', ''); ?>" style="width:100%;" />
                            </td>
                            <td>
                                <span style="color:red;"></span>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center;" colspan="2">
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_save()">保存</button>
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <button type="button" class="easyui-linkbutton" style="width:90px" onclick="do_reset()">重置</button>
                            </td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function() {

    });

    // 保存登录tips信息
    function do_save() {
        $('#fm-edit').form('submit', {
            url: '<?php echo $ctrl_url; ?>/post',
            onSubmit: function() {
                if($('#fm-edit input[name="name"]').val()=='') {
                    $.messager.alert('操作提示', '请输入姓名');
                    return false;
                }
                if($('#fm-edit input[name="age"]').val()=='') {
                    $.messager.alert('操作提示', '请输入年龄');
                    return false;
                }
                if($('#fm-edit input[name="sex"]').val()=='') {
                    $.messager.alert('操作提示', '请输入性别');
                    return false;
                }
                if($('#fm-edit input[name="phone"]').val()=='') {
                    $.messager.alert('操作提示', '请输入电话');
                    return false;
                }
                if($('#fm-edit input[name="address"]').val()=='') {
                    $.messager.alert('操作提示', '请输入地址');
                    return false;
                }
                if($('#fm-edit input[name="member_count"]').val()=='') {
                    $.messager.alert('操作提示', '请输入家庭成员数量');
                    return false;
                }
                return true;
            },
            success: function(result) {
                var result = $.parseJSON(result);
                var actionxm = $('#fm-edit input[name="actionxm"]').val();
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    cur_tips_id = result.data.tips_id;
                    $('#fm-edit input[name="actionxm"]').val('update');
                    $('#fm-edit input[name="tips_id"]').val(cur_tips_id);
                    $.messager.alert('操作提示', '保存成功', 'info', function() {
                        window.parent.dg_reload();
                        window.parent.change_panel('dg');
                    });
                }
            }
        })
    }
</script>

</body>
</html>
