<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array('jquery.easyui.extension/datagrid-detailview'),
        ));
        $ctrl_url = base_url('appointment/summary_list');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .dv-table td {
        border:0;
    }
    .dv-label {
        font-weight:bold;
        color:#15428B;
        width:100px;
    }
    .dv-table td {
        padding-bottom: 8px;
    }
    </style>
</head>
<body>
    <div id="p-dg" class="easyui-panel" title="预约管理" fit="true" border="false">
        <table id="dg" class="easyui-datagrid" title=""
               fit="true" border="false" plain="true"
               toolbar="#toolbar" multiSort="true"
               rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
               singleSelect="true" remote>
            <thead>
                <tr>
                    <th data-options="sortable:true,field:'id',width:50">编号</th>
                    <th data-options="sortable:true,field:'name',width:80">姓名</th>
                    <th data-options="sortable:true,field:'branch_name',width:60">预约分店</th>
                    <th data-options="sortable:true,field:'summary_time',width:130">预约时间</th>
                    <th data-options="sortable:true,field:'age',width:40">年龄</th>
                    <th data-options="sortable:true,field:'sex',width:40" formatter="format_sex">性别</th>
                    <th data-options="sortable:true,field:'phone',width:100">电话</th>
                    <th data-options="sortable:true,field:'wx_nickname',width:80">微信昵称</th>
                    <th data-options="sortable:true,field:'create_user_name',width:80">创建人</th>
                    <th data-options="sortable:true,field:'create_time',width:130">创建时间</th>
                    <th data-options="sortable:true,field:'update_user_name',width:80">更新人</th>
                    <th data-options="sortable:true,field:'update_time',width:130">更新时间</th>
                </tr>
            </thead>
        </table>

        <div id="toolbar" style="padding:2px 3px;">
            <form id="fm-search" method="post" novalidate>
                <div style="margin:3px 0;">
                    <?php if(!!$showBid) { ?>
                    预约分店：
                    <select id="branch_id" class="easyui-combobox" style="width:200px;" name="branch_id" data-options="valueField:'id',textField:'name'" panelHeight="auto" >
                    <?php } ?>
                    </select>
                    姓名：
                    <input id="title" class="easyui-textbox" style="width:100px" name="name">
                    电话：
                    <input id="title" class="easyui-textbox" style="width:100px" name="phone">
                    <span class="split-line">|</span>
                    <a class="easyui-linkbutton" iconCls="icon-search" onclick="do_search()" style="width:60px">搜索</a>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
    $(function() {
        $('#dg').datagrid({
            view: detailview,
            detailFormatter:function(index,row){
                return '<div class="ddv" style="padding:10px 0;"></div>';
            },
            onExpandRow: function(index,row){
                var ddv = $(this).datagrid('getRowDetail',index).find('div.ddv');
                ddv.panel({
                    border:false,
                    cache:false,
                    href: "<?php echo $ctrl_url.'/get?actionxm=details'; ?>&id=" + row.id,
                    onLoad:function(){
                        $('#dg').datagrid('fixDetailRowHeight',index);
                    }
                });
                $('#dg').datagrid('fixDetailRowHeight',index);
            }
        });

        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj
            });
        }, 100);

        // 加载模块名称下拉框
        $.ajax({
            url: '<?php echo base_url("sys/branch/get?actionxm=get_list"); ?>',
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                var new_data = new Array();
                new_data.push({"name":"不限", "id":-1, "selected":true});
                $.each(data, function(i, n) {
                    if(n.is_leaf) {
                        new_data.push({"name":'&nbsp;&nbsp;&nbsp;&nbsp;|-'+n.name, 'id': n.id});
                    } else {
                        new_data.push({"name":n.name, 'id': n.id});
                    }
                });
                $("#branch_id").combobox("loadData", new_data);
            }
        });

        $('#branch_id').combobox({
            onSelect: function(node) {
                console.log(node);
                var n = node.name.replace(/&nbsp;/ig, '');
                $('#branch_id').combobox('setText', n);
            }
        });
    });

    // 格式化性别
    function format_sex(value, row) {
        var rtn = '';
        switch(value) {
            case '1':
                rtn = '<span style="color:green;">男</span>';
                break;
            case '2':
                rtn = '<span style="color:red;">女</span>';
                break;
            default:
                rtn = '<span style="color:grey;">未知</span>';
                break;
        }
        return rtn;
    }
    </script>
</body>
</html>

