<div id="dlg-edit" class="easyui-dialog" style="width:350px;height:160px;padding:10px 20px"
    closed="true" modal="true" buttons="#dlg-edit-buttons" title="编辑表单">
    <form id="fm-edit" method="post" action="<?php echo base_url('customer/recept_regist/post')?>" novalidate>
        <input type="hidden" name="actionxm" value="">
        <table class="fm-table" cellpadding="4px">
            <colgroup>
                <col width="80px" /><col width="*" />
            </colgroup>
            <tr>
                <td>用户ID：</td>
                <td>
                    <input class="easyui-textbox" style="width:200px;" name="id" value="" readonly>
                </td>
            </tr>
            <tr>
                <td>新业务员：</td>
                <td>
                    <select id="selectSale" class="easyui-combobox" style="width:200px;" name="custId" data-options="valueField:'id',textField:'name'" panelHeight="auto" >
                </td>
            </tr>
        </table>
    </form>
</div>
<div id="dlg-edit-buttons">
    <button class="easyui-linkbutton w90" iconCls="icon-ok" onclick="do_save()">确定</button>
    <button class="easyui-linkbutton w90" iconCls="icon-cancel" onclick="javascript:$('#dlg-edit').dialog('close')">取消</button>
</div>
