<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array('jquery.easyui.extension/datagrid-detailview'),
        ));
        $ctrl_url = base_url('transaction/package_order');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .dv-table td {
        border:0;
    }
    .dv-label {
        font-weight: bold;
        color: #15428B;
        width: 120px;
    }
    .dv-table td {
        padding-bottom: 8px;
    }
    </style>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="套餐订单管理"
           fit="true" border="false" plain="true"
           url="<?php echo $ctrl_url . '/get?actionxm=search';?>" method="post"
           toolbar="#toolbar" multiSort="true"
           rownumbers="false" pagination="false"
           singleSelect="true" remote>
        <thead>
            <tr>
                <th data-options="sortable:true,field:'id',width:80">编号</th>
                <th data-options="sortable:true,field:'package_info',width:100">套餐</th>
                <th data-options="sortable:true,field:'userinfo',width:180">客户名称</th>
                <th data-options="sortable:true,field:'cust_info',width:80">业务员</th>
                <th data-options="sortable:true,field:'discount',width:80">折扣</th>
                <th data-options="sortable:true,field:'care_time',width:80">开始调理时间</th>
                <th data-options="sortable:true,field:'food_num',width:80">餐包数量</th>
                <th data-options="sortable:true,field:'create_user_name',width:100">创建人</th>
                <th data-options="sortable:true,field:'create_time',width:120">创建时间</th>
                <th data-options="sortable:true,field:'update_user_name',width:100">更新人</th>
                <th data-options="sortable:true,field:'update_time',width:120">更新时间</th>
            </tr>
        </thead>
    </table>

    <div id="toolbar">
        <button class="easyui-linkbutton" iconCls="icon-add"    plain="true" onclick="open_insert()">添加</button>
    </div>

    <?php $this->load->view('transaction/package_order_edit');?>

    <script type="text/javascript">

    $(function() {
        $('#dg').datagrid({
            view: detailview,
            detailFormatter:function(index,row){
                return '<div class="ddv" style="padding:10px 0;"></div>';
            },
            onExpandRow: function(index,row){
                var ddv = $(this).datagrid('getRowDetail',index).find('div.ddv');
                ddv.panel({
                    border:false,
                    cache:false,
                    href: "<?php echo $ctrl_url.'/get?actionxm=details'; ?>&id=" + row.id,
                    onLoad:function(){
                        $('#dg').datagrid('fixDetailRowHeight',index);
                    }
                });
                $('#dg').datagrid('fixDetailRowHeight',index);
            }
        });

        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: 'post',
                queryParams: obj
            });
            reload_umenu();
            reload_pmenu();
        }, 100);
    })

    // 格式化分店名称为树状
    function format_name(value, row) {
        if(row.level>0) {
            return '<span style="display:inline-block;padding-left:'+(20*row.level)+'px">|-'+value+'</span>';
        } else {
            return value;
        }
    }

    // 打开添加窗口
    function open_insert() {
        $('#fm-edit').form('clear').form('load', {actionxm:'insert', id:'系统编号', pid:0});
        $('#dlg-edit').dialog('setTitle', '订单添加').dialog('open');
    }

    // 保存操作
    function do_save() {
        $('#fm-edit').form('submit', {
            onSubmit: function() {
                return $(this).form('validate');
            },
            success: function(result) {
                var result = eval('('+result+')');
                if(result.success==false) {
                    $.messager.alert('操作提示', result.data, 'warning');
                } else {
                    $('#dlg-edit').dialog('close');
                    $('#dg').datagrid('reload');
                }
            }
        });
    }

    // 加载用户菜单
    function reload_umenu() {
        $.ajax({
            url: "<?php echo $ctrl_url . '/get?actionxm=getUserList';?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                var new_data = new Array();
                new_data.push({"name":"--请选择--", "id":-1, "selected":true});
                $.each(data, function(i, n) {
                    new_data.push({"name":n.name, 'id': n.id});
                });
                $("#uid").combobox("loadData", new_data);
            }
        });
    }

    // 加载套餐菜单
    function reload_pmenu() {
        $.ajax({
            url: "<?php echo $ctrl_url . '/get?actionxm=getPackageList';?>",
            type: 'get',
            datatype: 'json',
            success: function(result) {
                var data = $.parseJSON(result);
                var new_data = new Array();
                new_data.push({"name":"--请选择--", "id":-1, "selected":true});
                $.each(data, function(i, n) {
                    new_data.push({"name":n.name, 'id': n.id});
                });
                console.log(new_data);
                $("#pid").combobox("loadData", new_data);
            }
        });
    }

    </script>
</body>
</html>
